version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
  springboot-mongo:
    image: spring-app:1.1.0
    container_name: springboot-mongo
    ports:
      - 8080:8080
    links:
      - mongodb